### ISSUE TITLE
Current state of the project?

### ISSUE THREAD

**Issue by savq** [bfredl/Neovim.jl#12]
Hi,

I'm interested in using Neovim.jl for a project, but I haven't been able to do a build for Julia 1.6. (nor is it listed on the registry).

Is this project currently maintained? The last tagged release is from 2015, but there seem to have been some activity last year.

If the project is looking for maintenance/contributions, Is there a list of tasks that need to be done to put the project in a usable state?

Thanks for the info.

**Comment by bfredl** [comment]
it was lastly updated to 1.5 by @smolck (some stuff could still be broken but at least it builds) . Not sure how much needs to be changed for 1.6. what kind of errors do you get?

**Comment by smolck** [comment]
> If the project is looking for maintenance/contributions, Is there a list of tasks that need to be done to put the project in a usable state?

I was interested in updating the library after some talk about it on the Neovim gitter a while back, but I haven't touched it since (although this reminds me I should update the README and perhaps some other things). For tasks that need some work, see https://github.com/bfredl/Neovim.jl/pull/11#pullrequestreview-483693774 and also the second part of [this comment](https://github.com/bfredl/Neovim.jl/pull/11#issuecomment-688480974).

Also, this package isn't in Julia's package repository since it was written before that was really a thing, and I haven't submitted any PRs to add it, so that's another TODO.

> I'm interested in using Neovim.jl for a project, but I haven't been able to do a build for Julia 1.6. (nor is it listed on the registry).

EDIT: Just cloned the repo and tested it with `julia -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd())); Pkg.test("Neovim")'` with no issues. What's failing for you?

**Comment by savq** [comment]
>  what kind of errors do you get?

I get a list of several warnings when `using` the project:
```
WARNING: Method definition list_runtime_paths(Neovim.NvimClient{S} where S) in module Neovim overwritten.
  ** incremental compilation may be fatally broken for this module **
```

It then fails to connect to Neovim with `nvim_env`/`nvim_connect` because a function `connect` isn't defined
(ENV["NVIM_LISTEN_ADDRESS"] does work).

> For tasks that need some work, see #11 (review)

I'll take a look.

> I should update the README and perhaps some other things

That would be great. I'm somewhat familiar with the nvim API, but I haven't done a remote plugin before, and I'm a little bit lost with how it all fits together.

**Comment by smolck** [comment]
> I get a list of several warnings when `using` the project:

Hmm, I think for now those can be ignored; need to do some investigation into them (and probably read up on Julia so I can understand more what's happening 😅 ).

> It then fails to connect to Neovim with `nvim_env`/`nvim_connect` because a function `connect` isn't defined
> (ENV["NVIM_LISTEN_ADDRESS"] does work).

Should now be fixed in https://github.com/bfredl/Neovim.jl/commit/a44aa3b9ae38b44361211518000e48b6ffdadee2, mind testing it again?

**Comment by savq** [comment]
Yes, It works now.

I'll keep reporting minor problems here, and open and issue if I find a bigger problem.

Thanks for the quick response btw

**Comment by smolck** [comment]
Great! I'll go ahead and close this now, but definitely feel free to open an issue/comment here if you run into any further issues (or even just want help regarding how to use the library).
